name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
  validate_pyproject:
    name: Validate pyproject.toml
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install host dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --user --force \
            tox

    - name: Validate pyproject.toml
      run: |
        python -m tox -e validate_pyproject -vv

  lint:
    name: Lint code base
    needs: [validate_pyproject]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install host dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --user --force \
            tox

    - name: Pylint
      run: |
        python -m tox -e pylint -vv
    - name: Black
      run: |
        python -m tox -e blackcheck -vv

  unit_tests:
    name: Run unit tests
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install host dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --user --force \
            tox

    - name: unit tests with coverage
      run: |
        python --version
        python -m tox -e py3-coverage -vv

  integration_tests:
    name: Run integration tests
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install host dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --user --force \
            tox

    - name: integration tests
      run: |
        python --version
        python -m tox -e integration -vv
